# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: deploy_prac_development
#development:
#  <<: *default
#  database: db/development.sqlite3
test:
  <<: *default
  database: deploy_prac_test

production:
  adapter: postgresql
  database: deploy
  username: ubuntu
  password: password
