# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b102c742a1b08bc07d74b6c864c3fc926a0f9b63591cd7628dc6ff9b41a741af8f9540cb78f59aa29954bfba9e2ab8967fd0a31e1984f8d2faf58d14fbfc552

test:
  secret_key_base: 458be2e36a50f3b9c2bbb6caa08be89e736147fd74344417d34355245c3a5afae74b1b175195184407d38d60e534198fa91375e48f332abef54e5671b2992e89

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
